### DISCUSSION TITLE
Backup multiple databases?

### DISCUSSION THREAD

**Discussion by danielstonehouse** [elliotmatson/Docker-Davinci-Resolve-Project-Server#118] [General]
Thanks for this great project - after some false starts with Google cloud have got this running well on a geographically local cloud service based on Jelastic, and I am getting performance equivalent to our in house DaVinci server.

I know it goes against the docker philosophy but I installed Rclone to the running image to schedule sending the backups to google drive, which works well.

I noted it's easy to add new databases from Resolve - hoping someone can point me towards how to add more databases to the backup cycle? Or, even better, would it be possible to use a wildcard to backup all existing databases? The db's could use the same user / password credentials if that makes the process easier.

**Comment by elliotmatson** [comment]
This is a good idea, this project uses [this container](https://github.com/prodrigestivill/docker-postgres-backup-local) for backups, and it looks like they have added the ability to backup multiple db's. I'll take a look at their implementation!

**Reply by danielstonehouse** [reply]
@elliotmatson Would it be possible to back up multiple databases on the current version of your project? Even if it's on a running docker image that would allow me to push forward with my desired implementation.

Any ideas where I might start poking around?

**Reply by danielstonehouse** [reply]
This project seems like [the proper way to set up multiple databases ](https://github.com/boskomijin/postgres-multiple-databases-creation/tree/main)

**Reply by elliotmatson** [reply]
Yes, that would be how to create multiple databases, but to back up multiple, you would need to modify the docker compose file.
I'm thinking about how I can do this the "right" way, but here's a temp fix:

1. remove the `db-environment` set of env vars from the pgbackups service, like so:
  ```
    pgbackups:
      ...
      environment:
        <<: [*backup-environment]
        ...
  ```
2. Add the following to the `backup-environment` set of env vars:
```
x-common:
  ...
  backup: &backup-environment
    POSTGRES_DB: <comma separated list of all databases to backup>
    POSTGRES_USER: <same username as database section>
    POSTGRES_PASSWORD: <same password as database section>
    ...
```

So if I wanted to use the default compose setup that creates a database named "database", but also backup a database named "database2", this config should work:
```
x-common:
  database: &db-environment
    POSTGRES_DB: database
    POSTGRES_USER: &pg-user postgres
    POSTGRES_PASSWORD: DaVinci
    TZ: America/Chicago
    POSTGRES_LOCATION: &db-location "~/db:/var/lib/postgresql/data"
  backup: &backup-environment
    POSTGRES_DB: database,database2
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: DaVinci
    SCHEDULE: "@daily"
    BACKUP_KEEP_DAYS: 7
    BACKUP_KEEP_WEEKS: 4
    BACKUP_KEEP_MONTHS: 6
    BACKUP_LOCATION: &bk-location "~/backups:/backups"
  admin: &admin-environment
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: root
    PGADMIN_PORT: &pgadmin-port "3001:80"
```
