### ISSUE TITLE
Synology workarounds?

### ISSUE THREAD

**Issue by apvlv** [elliotmatson/Docker-Davinci-Resolve-Project-Server#5]
Hello, 

thank you very much for this project. On synology servers the psql port 5432 is internally in use and resolve itself (imho) is not able to connect to the db over custom defined ports. One workaround I found is use a macvlan network with docker to create a virtual interface but I'm feeling it is too much risk and overhead just for a port problem (see: https://www.schaupper.at/synology-davinci-resolve-shared-database/). 

do you know any other way to accomplish the project server install on synology?

Thank you!

**Comment by syakeef** [comment]
Another workaround is to **completely disable pgsql internally** in Synology. Though some of Synology's store app depend on it, such as Video Station, Download Station, etc. If your NAS depend on it I wouldn't suggest do this step.

### DSM 7
login via your ssh
`sudo -i` ; login as root account
`su - postgres` ; use postgres account
`pg_ctl -D /var/services/pgsql stop` ; this will stop running pgsql service
`exit` ; go back as root account
`systemctl stop pgsql` ; this stops pgsql
`systemctl stop pgsql-adapter` this stops running pgsql services
`systemctl mask pgsql` this will prevent pgsql from bootup
`systemctl mask pgsql-adapter` same as above

### DSM 6
DSM 6 uses synoservice, so replace `systemctl` command with : 
`/usr/syno/sbin/synoservice –stop pgsql` && etc

Then you can install this docker via docker-compose.
This works for me and I haven't had any system instability for weeks now

### Making it work on Synology
Ps. before using docker-compose, I recommend change and add a few docker yaml lines :

```yaml
services:
  postgres:
    image: postgres:13.0 ; using 13 defaults to the latest 13.7, which cause frequent database crash on my system
    shm_size: 4g ; this fix reindexdb out of memory issue when cleaning database using Resolve's optimize database (use 100m instead if your nas is limited in RAM)
    network_mode: "host" ; !!! BE SURE TO REMOVE 'ports : -  5432:5432' to avoid conflict !!!; without network host i couldn't get 2+ collaborators working together (Resolve will prompt network was blocked with firewall even though it wasn't)
    ...
  pgbackups:
    image: prodrigestivill/postgres-backup-local:13
    network_mode: "host" ; BE SURE TO REMOVE 'links : - postgres && depends on : - postgres' since we are using network host, this line isn't necessary and will cause conflict
  environment:
    - POSTGRES_HOST=localhost ; this will connect to our local nas ip for postgres backup
    ...
...
```
